name: CheeseStore CI
on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Generating pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          # fetch-depth: 0
      # 配置 Git
      # 主要是 quotePath，默认情况下，文件名包含中文时，git 会使用引号把文件名括起来，这会导致 action 中无法读取 :GitInfo 变量
      # - name: Git Configuration
      #   run: |
      #     git config --global core.quotePath false
      #     git config --global core.autocrlf false
      #     git config --global core.safecrlf true
      #     git config --global core.ignorecase false  
      # - uses: pnpm/action-setup@v2
      #   with:
      #     version: latest
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install dependencies
        run: pnpm install
      - name: Build pages
        run: pnpm run build
      - name: Deploy to website
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          git-config-name: Moni
          git-config-email: monishine_code@163.com
          token: ${{ secrets.MONISITE_BOT_TOKEN }}
          branch: pages # The branch the action should deploy to.
          folder: docs/.vitepress/dist # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch
          commit-message: update from CheeseStore